#include "definitions.hpp"

#ifndef HANDLE
	#define _DEFAULT_HANDLE
	#define HANDLE(el)
#endif

HANDLE(STCK_INIT)
HANDLE(STCK_DEINIT)
HANDLE(REG_TO_STCK)
HANDLE(STCK_TO_REG)
HANDLE(REG_TO_RVAL)
HANDLE(REG_FROM_REG)
HANDLE(INPUT_TO_REG)
HANDLE(OUTPUT_REG)
HANDLE(FUNC_RET)
HANDLE(EXIT_PROG)
HANDLE(CALL)
HANDLE(LABEL)
HANDLE(JUMP)
HANDLE(JUMP_EQ)
HANDLE(CMP_REG)
HANDLE(DEMAND_REG)
HANDLE(INIT_IMM)
HANDLE(ADD_IN_PLACE)
HANDLE(MUL_IN_PLACE)
HANDLE(SUB_IN_PLACE)
HANDLE(MOD_IN_PLACE)
HANDLE(DIV_IN_PLACE)
HANDLE(ALLOC_HEAP)
HANDLE(DEALLOC_HEAP)
HANDLE(READ_HEAP)
HANDLE(WRITE_HEAP)

#ifdef _DEFAULT_HANDLE
	#undef _DEFAULT_HANDLE
	#undef HANDLE
#endif

